version: '3.5'
services:
  federation-service:
    image: iotazebra/fed-catalogue-service
    env_file:
      - ./packages/fed-catalogue-rest-server/.env
    ports:
      - 3020:3020
    volumes:
      - ./.local-data-docker:/usr/src/app/.local-data
    restart: always
