version: '3.5'
services:
  federated-catalogue:
    image: twin.org/federated-catalogue:latest
    env_file:
      - ../.env.local
    ports:
      - 3020:3020
    volumes:
      - ./.local-data-docker:/usr/src/app/.local-data
    restart: always
